apiVersion: v1
kind: Namespace
metadata:
  name: sockets-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpbin
  namespace: sockets-test
  labels:
    app: tcpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpbin
  template:
    metadata:
      labels:
        app: tcpbin
    spec:
      containers:
        - name: tcpbin
          image: delusionaloptimist/tcpbin
          ports:
           - containerPort: 30000
             name: tcp-echo
           - containerPort: 30001
             name: tcp-info
           - containerPort: 40000
             name: udp-echo
           - containerPort: 40001
             name: udp-info
---
apiVersion: v1
kind: Service
metadata:
  name: tcpbin-service
  namespace: sockets-test
spec:
  selector:
    app: tcpbin
  ports:
    - protocol: TCP
      port: 30000
      targetPort: tcp-echo
      name: tcp-echo
    - protocol: TCP
      port: 30001
      targetPort: tcp-info
      name: tcp-info
    - protocol: UDP
      port: 40000
      targetPort: udp-echo
      name: udp-echo
    - protocol: UDP
      port: 40001
      targetPort: udp-info
      name: udp-info
